### PR TITLE
Fix mountall command

### LINKED ISSUE #972: Mount all fails
### Which version of blobfuse was used?
Main (fab7a3a2927285875409f6260ac0f816120f6a0a)

### Which OS distribution and version are you using?
Arch linux
Kernel version 6.0.7-arch1-1 (64-bit)

### If relevant, please share your mount command.
`blobfuse2 mount all --allow-other --foreground=true /run/media/azure --tmp-path=/tmp/blobfuse2 --log-level=LOG_DEBUG --config-file=config-file.yml`

### What was the issue encountered?
When executing the mount all command, none of the containers are mounted.
The error says something about container name not provided, but how is that necessary for a mount all command?
The authentication credentials are provided via environment variables and config looks as follows:
```yaml
components:
  - libfuse
  - stream
  - attr_cache
  - azstorage
```

### Have you found a mitigation/solution?
Mounting all containers separately with the same config and environment variables does work by providing an extra command line option `--container-name` for each of the containers.

### Please share logs if available.
```
Nov 10 09:37:08 mount-blobs.sh[28759]: Failed to mount container container3 : exit status 1
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [mount.go (363)]: mount : failed to initialize new pipeline [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [azstorage.go (94)]: AzStorage::Configure : Config validation failed [container name not provided]
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [mount.go (363)]: mount : failed to initialize new pipeline [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28787]: LOG_ERR [azstorage.go (94)]: AzStorage::Configure : Config validation failed [container name not provided]
Nov 10 09:37:08 blobfuse2[28787]: LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Nov 10 09:37:08 blobfuse2[28787]: LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Nov 10 09:37:08 blobfuse2[28787]: LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
Nov 10 09:37:08 blobfuse2[28787]: LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache
Nov 10 09:37:08 blobfuse2[28787]: LOG_INFO [stream.go (132)]: Stream::Configure : Buffer size 0, Block size 0, Handle limit 0
Nov 10 09:37:08 blobfuse2[28787]: LOG_INFO [read_write.go (58)]: ReadWriteCache::Configure : Streamonly set to true
Nov 10 09:37:08 blobfuse2[28787]: LOG_TRACE [stream.go (100)]: Stream::Configure : stream
Nov 10 09:37:08 blobfuse2[28787]: LOG_INFO [libfuse.go (251)]: Libfuse::Configure : read-only false, allow-other true, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: false
Nov 10 09:37:08 blobfuse2[28787]: LOG_TRACE [libfuse.go (217)]: Libfuse::Configure : libfuse
Nov 10 09:37:08 blobfuse2[28787]: LOG_CRIT [mount.go (360)]: Logging level set to : LOG_DEBUG
Nov 10 09:37:08 blobfuse2[28787]: LOG_CRIT [mount.go (359)]: Starting Blobfuse2 Mount : 2.0.0-preview.5 on [Arch Linux]
Nov 10 09:37:08 mount-blobs.sh[28759]: Mounting container : container3 to path : /run/media/azure/container3
Nov 10 09:37:08 mount-blobs.sh[28759]: Failed to mount container container2 : exit status 1
Nov 10 09:37:08 blobfuse2[28780]: LOG_ERR [mount.go (363)]: mount : failed to initialize new pipeline [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28780]: LOG_ERR [pipeline.go (69)]: Pipeline: error creating pipeline component azstorage [config error in azstorage [container name not provided]]
Nov 10 09:37:08 blobfuse2[28780]: LOG_ERR [azstorage.go (94)]: AzStorage::Configure : Config validation failed [container name not provided]
Nov 10 09:37:08 blobfuse2[28780]: LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Nov 10 09:37:08 blobfuse2[28780]: LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Nov 10 09:37:08 blobfuse2[28780]: LOG_INFO [attr_cache.go (145)]: AttrCache::Configure : cache-timeout 120, symlink false, cache-on-list true
Nov 10 09:37:08 blobfuse2[28780]: LOG_TRACE [attr_cache.go (121)]: AttrCache::Configure : attr_cache
Nov 10 09:37:08 blobfuse2[28780]: LOG_INFO [stream.go (132)]: Stream::Configure : Buffer size 0, Block size 0, Handle limit 0
Nov 10 09:37:08 blobfuse2[28780]: LOG_INFO [read_write.go (58)]: ReadWriteCache::Configure : Streamonly set to true
Nov 10 09:37:08 blobfuse2[28780]: LOG_TRACE [stream.go (100)]: Stream::Configure : stream
Nov 10 09:37:08 blobfuse2[28780]: LOG_INFO [libfuse.go (251)]: Libfuse::Configure : read-only false, allow-other true, default-perm 511, entry-timeout 120, attr-time 120, negative-timeout 120, ignore-open-flags: false
Nov 10 09:37:08 blobfuse2[28780]: LOG_TRACE [libfuse.go (217)]: Libfuse::Configure : libfuse
Nov 10 09:37:08 blobfuse2[28780]: LOG_CRIT [mount.go (360)]: Logging level set to : LOG_DEBUG
Nov 10 09:37:08 blobfuse2[28780]: LOG_CRIT [mount.go (359)]: Starting Blobfuse2 Mount : 2.0.0-preview.5 on [Arch Linux]
Nov 10 09:37:08 mount-blobs.sh[28759]: Mounting container : container2 to path : /run/media/azure/container2
Nov 10 09:37:08 mount-blobs.sh[28759]: Failed to mount container container1 : exit status 1
Nov 10 09:37:08 mount-blobs.sh[28759]: Mounting container : container1 to path : /run/media/azure/container1
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [azstorage.go (177)]: AzStorage::Stop : Stopping component azstorage
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [block_blob.go (238)]: BlockBlob::ListContainers : Listing containers
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [azstorage.go (164)]: AzStorage::Start : Starting component azstorage
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [block_blob.go (209)]: BlockBlob::TestPipeline : Validating
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [block_blob.go (260)]: BlockBlob::SetPrefixPath : path
Nov 10 09:37:08 blobfuse2[28759]: LOG_DEBUG [azauth.go (79)]: azAuth::getAzAuth : Account: accountname, AccountType: BLOCK, Protocol: https, Endpoint: https://accountname.blob.core.windows.net/
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [block_blob.go (135)]: BlockBlob::getCredential : Getting credential
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [block_blob.go (173)]: BlockBlob::SetupPipeline : Setting up
Nov 10 09:37:08 blobfuse2[28759]: LOG_INFO [config.go (469)]: ParseAndValidateConfig : Retry Config: Retry count 3, Max Timeout 3600, BackOff Time 1, Max Delay 3
Nov 10 09:37:08 blobfuse2[28759]: LOG_INFO [config.go (465)]: ParseAndValidateConfig : Account: accountname, Container: , AccountType: BLOCK, Auth: KEY, Prefix: , Endpoint: https://accountname.blob.core.wind>
Nov 10 09:37:08 blobfuse2[28759]: LOG_DEBUG [config.go (383)]: ParseAndValidateConfig : Getting auth type
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [config.go (477)]: ParseAndReadDynamicConfig : Reparsing config
Nov 10 09:37:08 blobfuse2[28759]: LOG_INFO [config.go (376)]: ParseAndValidateConfig : sdk logging from the config file: false
Nov 10 09:37:08 blobfuse2[28759]: LOG_INFO [config.go (372)]: ParseAndValidateConfig : using the following proxy address from the config file:
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [config.go (270)]: ParseAndValidateConfig : Parsing config
Nov 10 09:37:08 blobfuse2[28759]: LOG_TRACE [azstorage.go (83)]: AzStorage::Configure : azstorage
Nov 10 09:37:08 blobfuse2[28759]: LOG_CRIT [mount_all.go (155)]: Logging level set to : LOG_DEBUG
Nov 10 09:37:08 blobfuse2[28759]: LOG_CRIT [mount_all.go (154)]: Starting Blobfuse2 Mount All: 2.0.0-preview.5
Nov 10 09:37:08 systemd[1]: Started A virtual file system adapter for Azure Blob storage..
```

### PR DESCRIPTION
**Pull request by vibhansa-msft**
#972  fix

### CODE REVIEW

File: component/azstorage/block_blob.go [hunk 1]
```diff
@@ -378,7 +378,17 @@ func (bb *BlockBlob) RenameFile(source string, target string) error {
 	log.Trace("BlockBlob::RenameFile : %s -> %s done", source, target)
 
 	// Copy of the file is done so now delete the older file
-	return bb.DeleteFile(source)
+	err = bb.DeleteFile(source)
```
Comment (gapra-msft) [inline component/azstorage/block_blob.go:381]: Same with this change, we can leave that in it's own PR

File: cmd/mount_all.go [hunk 2]
```diff
@@ -264,7 +265,8 @@ func filterAllowedContainerList(containers []string) []string {
 // mountAllContainers : Iterate allowed container list and create config file and mount path for them
 func mountAllContainers(containerList []string, configFile string, mountPath string, configFileExists bool) error {
 	// Now iterate filtered container list and prepare mount path, temp path, and config file for them
-	fileCachePath := viper.GetString("file_cache.path")
+	fileCachePath := ""
```
Comment (gapra-msft) [inline cmd/mount_all.go:268]: is there any test we can add for this fix?

Comment (vibhansa-msft) [reply cmd/mount_all.go:268]: We can not because if you provide the path it will be set, if you dont then it will be empty. In no case its erroring out.
In case viper.GetString it used to fail if path is given on cli and work if it's given in config file.

**Review by gapra-msft — APPROVED** [review]

**Review by souravgupta-msft — APPROVED** [review]
