### PR TITLE
Symlink fix for ADLS accounts

### LINKED ISSUE #1243: Symlinks not working when mounting HNS-enabled blob storage usind ADLS
### Which version of blobfuse was used?
2.1.1-preview.1

### Which OS distribution and version are you using?
Ubuntu 22.04

### If relevant, please share your mount command.
`sudo blobfuse2 mount ${mount_dir} --config-file="/etc/blobfuse_${storage_container}_config.yml --use-adls=true"`

Config:
```# Common configurations
allow-other: true

# Logger configuration
logging:
  type: base
  level: log_debug
  file-path: '/.blobfuse2.log'
  max-file-size-mb: 512
  file-count: 10
  track-time: true

# Pipeline configuration. Choose components to be engaged. The order below is the priority order that needs to be followed.
components:
  - libfuse
  - stream
  - attr_cache
  - azstorage

# Libfuse configuration
libfuse:
  default-permission: '0666'
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

# Streaming configuration
stream:
  # If block-size-mb, blocks-per-file or cache-size-mb are 0, the stream component will not cache blocks.
  block-size-mb: 8
  max-buffers: 3
  buffer-size-mb: 512

# Attribute cache related configuration
attr_cache:
  timeout-sec: 7200

# Azure storage configuration
azstorage:
# Required
  type: adls
  account-name: ${storage_account}
  container: ${storage_container}
  endpoint: https://${storage_account}.blob.core.windows.net/
  # Optional
  block-size-mb: 16
  max-concurrency: 32
  mode: spn
  tenantid: ${tenantid}
  clientid: ${clientid}
  clientsecret: ${clientsecret}

# Health Monitor configuration
health_monitor:
  output-path: /var/log/
  enable-monitoring: true
  stats-poll-interval-sec: 10
  process-monitor-interval-sec: 30
  # list of monitors to be disabled
  monitor-disable-list:
    - cpu_profiler
    - memory_profiler
```

### What was the issue encountered?
The symlinks are not mounted. The name of the files appear but do no redirect to anything, `readlink` is empty, and `cd` returns `Error: Not a directory`.
Creating a symlink in the mounted directory after mounting also does not create a symlink, only a filename that appears when listing the directory.
Mounting the same storage using NFS instead of blobfuse does mount the symlinks. 
Mounting another storage with HNS-disabled storage account using `type: block` does mount symlinks

### Have you found a mitigation/solution?
Not using blobfuse.

### Please share logs if available.
The mount is successful so there is no error log, but the symlinks don't work.

### PR DESCRIPTION
**Pull request by souravgupta-msft**
Fixes #1243

- In ADLS accounts, read symlink fails after dir list operation. This is because the ADLS List API does not return metadata and other properties in its response (unlike blob API which does).
- To get the metadata, GetProperties() call is explicitly made after the List() operation for each blob.
- To enable symlink support in ADLS accounts, either pass `--no-symlinks=false` in the mount command or set `no-symlinks: false` in the config under attr_cache section.

### CODE REVIEW

File: component/azstorage/datalake.go [hunk 1]
```diff
@@ -495,41 +495,52 @@ func (dl *Datalake) List(prefix string, marker *string, count int32) ([]*interna
 
 	// Process the paths returned in this result segment (if the segment is empty, the loop body won't execute)
 	for _, pathInfo := range listPath.Paths {
-		var mode fs.FileMode
-		if pathInfo.Permissions != nil {
-			mode, err = getFileMode(*pathInfo.Permissions)
+		var attr *internal.ObjAttr
+
+		if dl.Config.disableSymlink {
+			var mode fs.FileMode
```
Comment (vibhansa-msft) [inline component/azstorage/datalake.go:501]: This peice shall be common. If disableSymlink is not there then we make an extra call to getAttr

**Review by vibhansa-msft — APPROVED** [review]
LGTM
