### PR TITLE
Fixing proxy URL parsing

### LINKED ISSUE #1402: Azure blob fuse via a proxy

### PR DESCRIPTION
**Pull request by souravgupta-msft**
Fixes #1402

### CODE REVIEW

File: component/azstorage/utils_test.go [hunk 1]
```diff
@@ -322,28 +322,32 @@ func (s *utilsTestSuite) TestSanitizeSASKey() {
...
+	opt, err := getAzBlobServiceClientOptions(&AzStorageConfig{})
+	assert.Nil(err)
 	assert.EqualValues(opt.Retry.MaxRetries, 0)
 	assert.GreaterOrEqual(len(opt.Logging.AllowedHeaders), 1)
 }
 
 func (s *utilsTestSuite) TestBlockProxyOptions() {
 	assert := assert.New(s.T())
-	opt := getAzBlobServiceClientOptions(&AzStorageConfig{proxyAddress: "127.0.0.1", maxRetries: 3})
+	opt, err := getAzBlobServiceClientOptions(&AzStorageConfig{proxyAddress: "127.0.0.1", maxRetries: 3})
```
Comment (vibhansa-msft) [inline component/azstorage/utils_test.go:333]: Add new cases for http://proxy and https://proxy

**Review by vibhansa-msft — APPROVED** [review]
